version: '3'

services:
  mcmipixyz:
    container_name: mcmipixyz
    image: chrismipi/mcmipixyz:latest
    environment:
      PORT: 5000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcmipixyz.entrypoints=http"
      - "traefik.http.routers.mcmipixyz.rule=Host(`mcmipi.xyz`)"
      - "traefik.http.middlewares.mcmipixyz-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mcmipixyz.middlewares=portainer-https-redirect"
      - "traefik.http.routers.mcmipixyz-secure.entrypoints=https"
      - "traefik.http.routers.mcmipixyz-secure.rule=Host(`mcmipi.xyz`)"
      - "traefik.http.routers.mcmipixyz-secure.tls=true"
      - "traefik.http.routers.mcmipixyz-secure.tls.certresolver=http"
      - "traefik.http.routers.mcmipixyz-secure.service=mcmipixyz"
      - "traefik.http.services.mcmipixyz.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"


networks:
  proxy:
    external: true